from abc import ABC


from .code_extraction import extract_answer_block, extract_last_function, extract_markdown_block

class Model(ABC):
    # This class is the parent class of all the models used in the project

    def __init__(self, model_name: str):
        # The parameter model_name is used to find wich model is used
        self.model_name = model_name

    def __str__(self):
        return f"{self.model_name}"

    def model_init(self):
        # This method is used to initialize the model, we want to do it once at the start
        pass

    def generate(self):
        # Children must have a generate method that will adapt the prompt for the model (if we need to use an
        # API or if we can make it run locally
        pass

    def extract(self):
        # The goal of this method is to extract the code from the text generated by the model.
        # The method needs to be implemented according to the generated text.
        pass

    @staticmethod
    def extract_code(text):
        #by priority
        code_in_answer_block = extract_answer_block(text)
        if code_in_answer_block:
            return code_in_answer_block
        code_in_markdown_block = extract_markdown_block(text)
        if code_in_markdown_block:
            return code_in_markdown_block
        return extract_last_function(text)

class TestModel(Model):
    # This class is used to test the Model class
    def __init__(self, model_name: str):
        # The parameter model_name is used to find wich model is used
        super().__init__(model_name)

    def __str__(self):
        return "TestModel"
    
    def generate(self, prompt):
        # This method is used to generate code from a prompt
        print(prompt)
        return "    return 1"

    def extract(self):
        # This method is used to extract the code from the text generated by the model
        pass
