### The goal of this files is to centralise all the classes and subclasses used in the project.


# Importing the necessary libraries
from abc import ABC



class Model(ABC):
    # This class is the parent class of all the models used in the project
    
    
    def __init__(self, model_name:str):
        # The parameter model_name is used to find wich model is used
        self.model_name = model_name
    
    def __str__(self):
        return f"{self.model_name}"
    
    def model_init(self):
        # This method is used to initialize the model, we want to do it once at the start
        pass
    def generate(self):
        # Children must have a generate method that will adapt the prompt for the model (if we need to use an 
        # API or if we can make it run locally
        pass
    
    def extract(self):
        # The goal of this method is to extract the code from the text generated by the model.
        # The method needs to be implemented according to the generated text.
        pass


