### The goal of this files is to centralise all the classes and subclasses used in the project.


# Importing the necessary libraries
from abc import ABC

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


class Model(ABC):
    # This class is the parent class of all the models used in the project
    
    
    def __init__(self, model_name:str):
        # The parameter model_name is used to find wich model is used
        self.model_name = model_name
    
    def __str__(self):
        return f"{self.model_name}"
    
    def model_init(self):
        # This method is used to initialize the model, we want to do it once at the start
        pass
    def generate(self):
        # Children must have a generate method that will adapt the prompt for the model (if we need to use an 
        # API or if we can make it run locally
        pass
    
    def extract(self):
        # The goal of this method is to extract the code from the text generated by the model.
        # The method needs to be implemented according to the generated text.
        pass


class HuggingFace(Model):
    # This class can be used to use an open source model that is available on the HuggingFace library
    
    
    def __init__(self, model_name:str, model_path:str):
        # The parameter model_name is used to find wich model is used
        self.model_name = model_name
        self.model_path = model_path
        
        
    
    def __str__(self):
        return f"{self.model_name}"
    
    def model_init(self,cachedir=None):
        # This method is used to initialize the model, we want to do it once at the start
        self.__tokenizer = AutoTokenizer.from_pretrained(self.model_path, cachedir=cachedir)
        self.__model = AutoModelForCausalLM.from_pretrained(self.model_path, cachedir=cachedir).to(torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu"))
        
    def generate(self, prompt, max_tokens=100, top_p=0.95, top_k=60, temperature=0.3):
        # This method is used to generate the code from a prompt in the chat model. Do not use this for batch generation.
        
        chat_input = self.__tokenizer.apply_chat_template(prompt, tokenize=False, add_generation_prompt=True)
        inputs = self.__tokenizer(chat_input, return_tensors="pt", add_special_tokens=True).to(self.__model.device)
        
        tokens = self.__model.generate(**inputs, max_new_tokens=max_tokens, do_sample=True, top_p=top_p, top_k=top_k, temperature=temperature)
        
        return self.extract(self.__tokenizer.decode(tokens[0], skip_special_tokens=True))
    
    def generate_batch(self, prompts, max_tokens=100, top_p=0.95, top_k=60, temperature=0.3):
        # This method is used to generate the code from a list of prompts in the chat model. Use this for batch generation.
        
        chat_input = [self.__tokenizer.apply_chat_template(prompts[i], tokenize=False, add_generation_prompt=True) for i in range(len(prompts))]
        inputs = self.__tokenizer(chat_input, return_tensors="pt", add_special_tokens=True, padding = True).to(self.__model.device)
        
        tokens = self.__model.generate(**inputs, max_new_tokens=max_tokens, do_sample=True, top_p=top_p, top_k=top_k, temperature=temperature)
        decoded = self.__tokenizer.batch_decode(tokens, skip_special_tokens=True)
        
        return [self.extract(decoded[i]) for i in range(len(tokens)) ]
    
    def extract(self, text):
        # The goal of this method is to extract the code from the text generated by the model.
        # The method needs to be implemented according to the generated text.
        return text


